// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzjmuvfswpirtjdlrlbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6am11dmZzd3BpcnRqZGxybGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MDEwMDQsImV4cCI6MjA1NTA3NzAwNH0.0BiSnFrkGv73lMy3DxxXWlACA8mQw7GGvBcO7kXkEFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);